name:                yumegamehs
version:             0.1.0.0
github:              "aidatorajiro/yumegame"
license:             GPLv3
author:              "Torajiro Aida"
maintainer:          "kawarusosu@zoho.com"
copyright:           "2024 Torajiro Aida"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/aidatorajiro/yumegame#readme>

dependencies:
- base >= 4.7 && < 5
- network
- bytestring
- Yampa
- binary
- lens
- clock
- sdl2
- stm
- vector
- template-haskell
- string-qq
- json
- extra
- array
- random
- text
- lens-aeson
- aeson

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  yumegamehs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yumegamehs

tests:
  yumegamehs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - yumegamehs
